spring.application.name=MatLadan

## DATABASE :: SUPABASE ##
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.hikari.maximum-pool-size=5 

## JPA / HIBERNATE ###
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

## For testing purposes, H2, local database ##


## FlyWay ###
## Remember to put the FlyWay to false when you are using the test ##
spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=true

## Server Connection ###
## Default is 8080 so we use that ##
server.port=8080

